version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "433:433"
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./nginx/wordpress.conf:/etc/nginx/conf.d/wordpress.conf
      - ./wordpress:/var/www/html
      - ./api:/var/www/api
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - wordpress
      - api

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456

  wordpress:
    build:
      context: .
      dockerfile: ./config/api-config/wordpress.dockerfile
    depends_on:
      - db
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress

  api:
    build:
      context: .
      dockerfile: ./config/api-config/api.dockerfile
    volumes:
      - ./api:/var/www/api
    container_name: api
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: wordpress
      DB_USERNAME: admin
      DB_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  wordpress:
