version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: ngnix
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - ./api:/var/www/api
    depends_on:
      - wordpress
  
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: db_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: db_test

  api:
    build:
      dockerfile: ./config/api-config/Dockerfile
    volumes:
      - ./api:/var/www/api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db_test
      DB_USERNAME: admin
      DB_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
  wordpress:
